config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: redirect('/products')

  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show] do
    resources :products, only: [:index]  # Nested route for products by category
  end

  resource :cart, only: [:show, :destroy]  # Singular resource for cart
  resources :line_items, only: [:create, :update, :destroy] do
    member do
      patch 'decrement'
    end
  end

  get '/admin', to: 'admin_dashboard#index'
  get 'up', to: 'rails/health#show', as: :rails_health_check

  resources :customers
  resources :orders, only: [:new, :create, :index] do
    member do
      get 'success'
      get 'show_invoice'
    end
  end

  get '/contact', to: 'static_pages#show', defaults: { title: 'Contact' }
  get '/about', to: 'static_pages#show', defaults: { title: 'About' }
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :province
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_one :order
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product: product, quantity: 1)
    end
    current_item.save
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products  
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy

  validates :name, :address, :province, :city, :postal_code, presence: true
end

app/models/line_item.rb
# app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cart
  has_many :line_items, through: :cart

  validates :total_amount, presence: true
  validates :user_id, presence: true

  # Add this method to allow searching through these associations
  def self.ransackable_associations(auth_object = nil)
    ["cart", "user"]
  end

  # Add this method to allow specific attributes to be searchable
  def self.ransackable_attributes(auth_object = nil)
    ["total_amount", "address", "province", "street", "payment_status", "payment_id", "created_at"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :category
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  validates :category_id, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
  def self.ransackable_attributes(_auth_object = nil)
    %w[content created_at id title updated_at]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders

  validates :street, :province, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:show, :destroy]

  def show
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to root_path, notice: 'Your cart is currently empty.'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/index.html.erb
<div class="container">
  <h1 class="my-4">Product Categories</h1>

  <div class="card shadow">
    <div class="card-body">
      <ul class="list-group">
        <% @categories.each do |category| %>
          <li class="list-group-item">
            <%= link_to category.name, category_path(category) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<!-- app/views/categories/show.html.erb -->

<div class="container">
  <h1 class="my-4">Products in <%= @category.name %></h1>

  <div class="card shadow">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Price</th>
              <th scope="col" class="text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= product.name %></td>
                <td><%= product.description %></td>
                <td><%= number_to_currency(product.price) %></td>
                <td class="text-center">
                  <%= link_to 'Details', product_path(product), class: 'btn btn-sm btn-info mr-2' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>


  <%= paginate @products %>
</div>